### ISSUE TITLE
Cast payload string to its configured type.

### ISSUE THREAD

**Issue by mrsteakhouse** [tim-hellhake/homie-adapter#10]
When setting the payload directly as string to a number property, the logs do not work as the upper scale is always NaN.
Since we already know at that point which type the payload must have, it can simply be cast before updating the property.
If everyone is okay with it, i will have a look at this.

**Comment by tim-hellhake** [comment]
> If everyone is okay with it, i will have a look at this.

Sure go ahead!
If you need help, just ping me.
